# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

includes:
  bff:
    dir: ./bff
    taskfile: ./bff/Taskfile.yml
  api:
    dir: ./api
    taskfile: ./api/Taskfile.yml

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  semgrep:
    desc: Run Semgrep to analyze the codebase
    cmds:
      - uvx semgrep --config auto .

  lint:
    desc: Run all lint checks
    cmds:
      - task: semgrep
      - task: api:lint
      - task: bff:lint

  build:
    desc: Run all build checks
    cmds:
      - task: api:build
      - task: bff:build

  test:
    desc: Run all tests
    cmds:
      - task: api:test
      - task: bff:test

  ci:
    desc: Run all CI checks (lint, build, test)
    cmds:
      - task: lint
        ignore_error: true
      - task: build
        ignore_error: true
      - task: test
        ignore_error: true

  setup:
    desc: Setup the project
    cmds:
      - cmd: echo "Setting up the project..."
      - cmd: aqua install
      - task: api:setup
      - task: bff:setup
