from typing import Protocol
from uuid import UUID

from app.domain.entities.post import Post


class PostRepository(Protocol):
    async def get_by_id(self, post_id: UUID) -> Post | None: ...
    async def list_by_author(self, author_id: UUID) -> list[Post]: ...
    async def list_all(self, limit: int = 20, offset: int = 0) -> list[Post]: ...
    async def add(self, post: Post) -> None: ...
    async def save(self, post: Post) -> None: ...
